import * as fs from 'fs';
import * as core from '@actions/core';
import { CardType, RepoStatsConfig } from '../types';

const START_MARKER = '<!-- REPOSTATS:START -->';
const END_MARKER = '<!-- REPOSTATS:END -->';

export function updateReadme(config: RepoStatsConfig, generatedCards: CardType[]): boolean {
  const { readmePath, outputDir, columns } = config;

  if (!fs.existsSync(readmePath)) {
    core.warning(`README not found at ${readmePath}. Skipping README update.`);
    return false;
  }

  let content = fs.readFileSync(readmePath, 'utf-8');
  const block = buildBlock(generatedCards, outputDir, columns);

  const markerRegex = /<!-- REPOSTATS:START -->[\s\S]*?<!-- REPOSTATS:END -->/;

  if (markerRegex.test(content)) {
    content = content.replace(markerRegex, block);
  } else {
    content = content.trimEnd() + '\n\n' + block + '\n';
  }

  fs.writeFileSync(readmePath, content, 'utf-8');
  core.info(`Updated ${readmePath} with ${generatedCards.length} stat cards.`);
  return true;
}

function buildBlock(cards: CardType[], outputDir: string, columns: 1 | 2): string {
  const lines: string[] = [];
  lines.push(START_MARKER);
  lines.push('<!-- This section is auto-generated by RepoStats. Do not edit manually. -->');

  if (columns === 1) {
    for (const card of cards) {
      lines.push(`<p align="center">`);
      lines.push(`  <img src="${outputDir}/${card}.svg" alt="${cardLabel(card)}" />`);
      lines.push(`</p>`);
    }
  } else {
    // 2-column layout: pair cards
    for (let i = 0; i < cards.length; i += 2) {
      lines.push(`<p align="center">`);
      lines.push(`  <img src="${outputDir}/${cards[i]}.svg" alt="${cardLabel(cards[i])}" width="49%" />`);
      if (i + 1 < cards.length) {
        lines.push(`  <img src="${outputDir}/${cards[i + 1]}.svg" alt="${cardLabel(cards[i + 1])}" width="49%" />`);
      }
      lines.push(`</p>`);
    }
  }

  lines.push(END_MARKER);
  return lines.join('\n');
}

function cardLabel(type: CardType): string {
  return type
    .split('-')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}
