import { CardType } from '../types';

export function buildReadmeBlock(cards: CardType[], outputDir: string, columns: 1 | 2): string {
  const lines: string[] = [];
  lines.push('<!-- REPOSTATS:START -->');
  lines.push('<!-- This section is auto-generated by RepoStats. Do not edit manually. -->');

  if (columns === 1) {
    for (const card of cards) {
      lines.push(`<p align="center">`);
      lines.push(`  <img src="${outputDir}/${card}.svg" alt="${cardLabel(card)}" />`);
      lines.push(`</p>`);
    }
  } else {
    for (let i = 0; i < cards.length; i += 2) {
      lines.push(`<p align="center">`);
      lines.push(`  <img src="${outputDir}/${cards[i]}.svg" alt="${cardLabel(cards[i])}" width="49%" />`);
      if (i + 1 < cards.length) {
        lines.push(`  <img src="${outputDir}/${cards[i + 1]}.svg" alt="${cardLabel(cards[i + 1])}" width="49%" />`);
      }
      lines.push(`</p>`);
    }
  }

  lines.push('<!-- REPOSTATS:END -->');
  return lines.join('\n');
}

function cardLabel(type: CardType): string {
  return type
    .split('-')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}
