import { ThemeVars } from '../types';

export interface CardOptions {
  title: string;
  width: number;
  height: number;
  body: string;
  theme: ThemeVars;
  icon?: string;
}

export function renderCard({ title, width, height, body, theme, icon }: CardOptions): string {
  const titleBarHeight = 36;
  const padding = 20;
  const totalHeight = height + titleBarHeight + padding;

  const titleId = `repostats-${title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`;

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${totalHeight}" viewBox="0 0 ${width} ${totalHeight}" fill="none" role="img" aria-labelledby="${titleId}">
  <title id="${titleId}">${escapeXml(title)}</title>
  <style>
    .card-bg { fill: ${theme.bg}; }
    .card-border { stroke: ${theme.border}; stroke-width: 1; fill: none; }
    .card-title { font: 600 14px 'Segoe UI', Ubuntu, 'Helvetica Neue', sans-serif; fill: ${theme.text}; }
    .card-text { font: 400 12px 'Segoe UI', Ubuntu, 'Helvetica Neue', sans-serif; fill: ${theme.text}; }
    .card-text-secondary { font: 400 11px 'Segoe UI', Ubuntu, 'Helvetica Neue', sans-serif; fill: ${theme.textSecondary}; }
    .card-accent { fill: ${theme.accent}; }
    .card-footer { font: 400 9px 'Segoe UI', Ubuntu, 'Helvetica Neue', sans-serif; fill: ${theme.textSecondary}; }
  </style>
  <rect class="card-bg card-border" x="0.5" y="0.5" width="${width - 1}" height="${totalHeight - 1}" rx="6" />
  <g transform="translate(${padding}, 24)">
    ${icon ? `<text class="card-title" x="0" y="0">${icon} ${escapeXml(title)}</text>` : `<text class="card-title" x="0" y="0">${escapeXml(title)}</text>`}
  </g>
  <line x1="${padding}" y1="${titleBarHeight}" x2="${width - padding}" y2="${titleBarHeight}" stroke="${theme.border}" stroke-width="0.5" />
  <g transform="translate(${padding}, ${titleBarHeight + 12})">
    ${body}
  </g>
  <text class="card-footer" x="${width - padding}" y="${totalHeight - 6}" text-anchor="end">Generated by RepoStats</text>
</svg>`;
}

export function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
